services:
  - type: web
    name: pm-tool-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: "https://pm-tool-frontend.onrender.com"
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

  - type: web
    name: pm-tool-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: "https://pm-tool-backend.onrender.com"
